### PR TITLE
Fixed grammatical errors 

### PR DESCRIPTION
**Pull request by LoftyDroid**
I have come across some grammatical errors in this readme so I have corrected them.

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
Great work, Ahmed!

**Comment by MrKrishnaAgarwal** [comment]
Hi @LoftyDroid 
Could you please resolve the conflicts else I will not be able to merge the PR. 
if you aren’t able to do, just make a new PR.

**Comment by MrKrishnaAgarwal** [comment]
@LoftyDroid Please make a new PR and fix those grammatical errors.

**Comment by LoftyDroid** [comment]
okay sure!

**Pull request closed without merging**
