### PR TITLE
New PR and fixed grammatical errors done

### PR DESCRIPTION
**Pull request by LoftyDroid**
Here is the new PR and I have fixed the grammatical errors in readme.

### CODE REVIEW

**Comment by LoftyDroid** [comment]
hmm, what is pre-commit? how do I resolve it?

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
there is nothing that is changed!!

**Comment by MrKrishnaAgarwal** [comment]
> Here is the new PR and I have fixed the grammatical errors in readme.

I can't see any fixes, please visit **Files Changed** tab and see.

**Comment by LoftyDroid** [comment]
Okay

**Pull request closed without merging**
